version: '3.8'
services:
  apache:
    container_name: apache
    build: ./docker/apache
    links:
      - php
    volumes:
      - ./public:/usr/local/apache2/htdocs
    ports:
      - '80:80'
  php:
    container_name: php
    build: ./docker/php
    depends_on:
      - db
    volumes:
      - ./public:/usr/local/apache2/htdocs
    working_dir: /usr/local/apache2/htdocs
    ports:
      - '9000:9000'
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: przemyslenia
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '9906:3306'
    volumes:
      - ./przemyslenia.sql:/docker-entrypoint-initdb.d/przemyslenia.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
